#!/bin/sh

# Desktop Environment?
# nih, continuation of nihwm

# Functions

iscommand() {
	if ! [ -x $(command -v $1) ]; then
		echo "$1 is not installed."
		exit 1
	fi
}

# Checking command availability
iscommand startx
iscommand nihwm
#iscommand picom # TODO changea picom to nihcomp

# Checking variables

if [ -z "${DISPLAY+x}" ]; then
	exec startx $0	
fi

if [ "$DESKTOP_SESSION" = "nih" ]; then
	echo $0 is already running, abort.
	exit 1
fi

# Change GTK/KDE theme
# if [ -f '~/.config/gtk-3.0/settings.ini' ]; then
#	sed 's/gtk-theme-name=.*/gtk-theme-name=Adwaita-dark/g' '~/.config/gtk-3.0/settings.ini' | tee '~/.config/gtk-3.0/settings.ini' 
# fi

# X definitions
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f "$sysresources" ]; then
    xrdb -merge $sysresources
fi
if [ -f "$sysmodmap" ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

mkdir -p $HOME/.nihwm

# Export
export EDITOR=vim
export EDITORS=vim
export EXPLORER=thunar
export xterm=kitty 

export XDG_CURRENT_DESKTOP="nih"
export DESKTOP_SESSION="nih"
export NIH_VERSION=$(nihwm -v)

# Set X
xset r rate 250 100 &

# Configuration
iwctl device wlan0 set-property Powered on &
# mmcli device

# Setup
feh --bg-scale $HOME/wallpaper.png & # TODO add a carousel inside ~/wallpapers/
picom -b & # TODO use PhyOS's fork
nihwm > $HOME/.nihwm/log.txt 

unset XDG_CURRENT_DESKTOP
unset DESKTOP_SESSION
unset DISPLAY
unset NIH_VERSION
