#!/bin/sh

# Desktop Environment?
# nih, continuation of nihwm

# Functions

iscommand() {
	if ! [ -x $(command -v $1) ]; then
		echo "$1 is not installed."
		echo "Please install it using the install script or the installer."
		exit 1
	fi
}

isoptional() {
	if ! [ -x $(command -v $1) ]; then
		echo "$1 is not installed."
		echo "Please install it using the install script or the installer even though it is optional."
	fi
}

# Checking command availability
iscommand startx
iscommand nihwm
iscommand nihwmctl
iscommand nih-polkit # TODO should I change this to nihpolkit
iscommand picom # TODO change picom to nihcomp

#iscommand thunar # default file manager 
iscommand dmenu
iscommand kitty
iscommand rofi

# Checking command optionally
isoptional emoji-selector # from aishki/tools
isoptional wineboot

# Checking variable

# If there is no display (at tty->nih, run startx)
if [ -z "${DISPLAY+x}" ]; then
	exec startx $0	
fi

if [ "$DESKTOP_SESSION" = "nih" ]; then
	echo "$0 is already running, abort."
	exit 1
fi

# Change GTK/KDE theme
# if [ -f '~/.config/gtk-3.0/settings.ini' ]; then
#	sed 's/gtk-theme-name=.*/gtk-theme-name=Adwaita-dark/g' '~/.config/gtk-3.0/settings.ini' | tee '~/.config/gtk-3.0/settings.ini' 
# fi

echo "[$(date)] :: starting nihwm from nih" > $HOME/.nihwm/log.txt

# X definitions
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"

# merge in defaults and keymaps
if [ -f "$sysresources" ]; then
    xrdb -merge $sysresources
fi
if [ -f "$sysmodmap" ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Directories
mkdir -p $HOME/.nihwm

# Export
export EDITOR=nvim
export EDITORS=nvim
export EXPLORER=thunar
export xterm=kitty 

export XDG_CURRENT_DESKTOP="nih"
export DESKTOP_SESSION="nih"
export NIH_VERSION=$(nihwm -v)

# XDG supports
# export XDG_CONFIG_HOME="$HOME/.config"

# Styling
export GTK_THEME="Adwaita:dark"
export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
export QT_STYLE_OVERRIDE=adwaita-dark

# Set X
xset r rate 250 100

# Configuration
ifconfig wlan0 up
iwctl device wlan0 set-property Powered on
# mmcli device

# Sound setup
jack_control start &

# Other setup
if  [ -x $(command -v wineboot) ]; then
	echo Using wineboot to update >> $HOME/.nihwm/log.txt
	wineboot --update >> $HOME/.nihwm/log.txt &
fi

# Other environment setup
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

# Setup
feh --bg-scale $HOME/wallpaper.png & # TODO add a carousel inside ~/wallpapers/
picom -b & # TODO use PhyOS's fork
nih-polkit &
nihwm >> $HOME/.nihwm/log.txt # Do not exec 

echo "[$(date)] :: nihwm closed" >> $HOME/.nihwm/log.txt

