#!/usr/bin/sh

#define VERSION 0.11

# The X Set Root
# Display Style here

# Is this shit bloated? I hope not
# This is very slow UwU

# Should I use C? The lazy thing is that I am not sure if
# combining C with programs/forking is a good idea

# TODO make this unbloated

battery_notified=false

iscommand() {
	if ! [ -x $(command -v $1) ]; then
		echo "$1 is not installed."
		exit 1
	fi
}

# TODO optimize this

if [ "$#" -le 1 ]; then
	1="statusbar"
fi;

graceful_close() {

rofi -show window -theme nihwm-theme &

OIFS="$IFS"
IFS=$'\n'
for p in $(wmctrl -l); do
	program=$(echo $p | awk 'BEGIN {ORS = " ";} {for ( i = 4; i <= NF; i++ ) print $i;}' | sed 's/ $//g' )
	echo "Asking to die peacefully to program \"$program\""
	wmctrl -c $program
done

IFS="$OIFS"

while [ $(wmctrl -l | wc -l) -gt 1 ] ; do
	echo Waiting...
	sleep 0.5
done

}

if [ "$1" = "logoutmenu" ]; then

option=$(printf "shutdown\nreboot\nlogout\n" | dmenu)

# No case ... esac
if [ "$option" = "shutdown" ]; then
	graceful_close
	shutdown -P 0
elif [ "$option" = "logout" ]; then
	graceful_close
	kill nihwm # TODO should I use/invoke Mod-Shift-Cmd-Q?
elif [ "$option" = "reboot" ]; then
	graceful_close
	shutdown r -P 0
fi

elif [ "$1" = "shutdown" ]; then # SHUTDOWN

graceful_close

shutdown -P 0

exit 1

elif [ "$1" = "reboot" ]; then # REBOOT

graceful_close

shutdown r -P 0

## THIS IS WHERE NIHWM's STATUSBAR is DEFINED ##
elif [ "$1" = "statusbar" ]; then # STATUSBAR

while true
do

	# Only use Right because of Mono
	volume=$(amixer get Master | grep 'Right:.*\(.*\)' | cut -d" " -f7)

	# Battery
	battery=$(upower -i $(upower -e | grep 'BAT') | grep 'percentage' | cut -d " " -f15)

	# Is Capslock
	caps=$(xset q | grep 'Caps Lock' | awk '{print $4}')
	if [ "$caps" = "on" ]; then
		caps='C'
	else
		caps=''
	fi

	# Is NumLock
	nums=$(xset q | grep 'Nums Lock' | awk '{print $8}')
	if [ "$nums" = "on" ]; then
		nums='N'
	else
		nums=''
	fi

	# Is Focus On Switch
	focusmode=$(xprop -root _NIHWM_FOCUS_CHANGE | cut -d"=" -f2)
	if [ "$focusmode" = ' 1' ]; then
		focusmode='F'
	else
		focusmode=''
	fi

	# Compositor
	compositoractive=$(xprop -root _NIHWM_USING_COMPOSITOR | cut -d"=" -f2)
	if [ "$compositoractive" = ' 1' ]; then
		compositoractive='@'
	else
		compositoractive=''
	fi

	# Attach below
	attachbelow=$(xprop -root _NIHWM_ATTACH_BELOW | cut -d"=" -f2)
	if [ "$attachbelow" = ' 1' ]; then
		attachbelow='a'
	else
		attachbelow=''
	fi

	# Allow next floating
	allownextfloating=$(xprop -root _NIHWM_ALLOW_NEXT_FLOATING | cut -d"=" -f2)
	if [ "$allownextfloating" = ' 1' ]; then
		allownextfloating='_'
	else
		allownextfloating=''
	fi

	# Allow next floating
	showoverlay=$(xprop -root _NIHWM_SHOW_OVERLAY | cut -d"=" -f2)
	if [ "$showoverlay" = ' 1' ]; then
		showoverlay='w'
	else
		showoverlay=''
	fi

	# Ignore master focus in stack
	ignoremasterfocus=$(xprop -root _NIHWM_IGNORE_MASTER_FOCUS | cut -d"=" -f2)
	if [ "$ignoremasterfocus" = ' 1' ]; then
		ignoremasterfocus='M'
	else
		ignoremasterfocus=''
	fi

	# Ignore master focus in stack
	iscursorwarp=$(xprop -root _NIHWM_CURSOR_WARP | cut -d"=" -f2)
	if [ "$iscursorwarp" = ' 1' ]; then
		iscursorwarp='^'
	else
		iscursorwarp=''
	fi

	# Battery checker
	if [ "${battery%?}" -le "20"  ] && [ "$battery_notified" = "false" ]; then
		notify-send --urgency=critical -t 0 --icon=battery "Battery is low" "<span font='50px'>Please charge your Laptop's battery or use the cable while your laptop is still on.</span>"
		battery_notified=true
	fi

	# All the rules, capslock, et cetera
	condition="${nums}${caps}${showoverlay}${iscursorwarp}${ignoremasterfocus}${allownextfloating}${focusmode}${compositoractive}${attachbelow}"
	
	# Set status bar
	! xsetroot -name "[$condition] | $(date) | ${volume} | ${battery} | nihwm" && exit 69

	sleep 0.1
done

exit 0

fi
